In [5]:
import torch

In [63]:
# Load saved data
metadata = torch.load('155456_26062019_checkpoints/metadata.pth')
model = torch.load('155456_26062019_checkpoints/checkpoint_8.pth', map_location='cpu')

In [64]:
print("METADATA KEYS:")
print("--------------")
for key in metadata:
    print(key)
    
print("\nCHECKPOINT 1 KEYS:")
print("--------------")
for key in model:
    print(key)

METADATA KEYS:
--------------
vocabulary
index_to_document

CHECKPOINT 1 KEYS:
--------------
epoch
model_state_dict
optimizer_state_dict
loss


In [67]:
def get_idx2vec():
    idx2vec = dict()
    with open(r"155456_26062019_checkpoints/00008/DPEs/tensors.tsv", "r") as f:
        for i, line in enumerate(f):
            vec = line.replace('\n', '').split('\t')
            vec = torch.tensor([float(x) for x in vec])
            idx2vec[str(i)] = vec
    return idx2vec

In [68]:
idx2vec = get_idx2vec()
idx2doc = metadata['index_to_document']

In [69]:
for key in idx2doc:
    print('ID:', key)
    print('PKG:', idx2doc[key])
    print('VEC:\n',idx2vec[key])
    print()

ID: 0
PKG: 0-0-1
VEC:
 tensor([0.0161, 0.0151, 0.0146, 0.0151, 0.0155, 0.0162, 0.0147, 0.0161, 0.0149,
        0.0159, 0.0152, 0.0150, 0.0156, 0.0158, 0.0167, 0.0164, 0.0158, 0.0146,
        0.0156, 0.0158, 0.0159, 0.0153, 0.0147, 0.0159, 0.0160, 0.0164, 0.0157,
        0.0147, 0.0158, 0.0156, 0.0155, 0.0156, 0.0160, 0.0162, 0.0157, 0.0151,
        0.0159, 0.0165, 0.0165, 0.0153, 0.0158, 0.0155, 0.0152, 0.0158, 0.0149,
        0.0150, 0.0168, 0.0151, 0.0156, 0.0159, 0.0157, 0.0162, 0.0157, 0.0160,
        0.0150, 0.0157, 0.0151, 0.0152, 0.0161, 0.0159, 0.0156, 0.0156, 0.0157,
        0.0156])

ID: 1
PKG: 0-core-client
VEC:
 tensor([0.0161, 0.0151, 0.0146, 0.0151, 0.0155, 0.0162, 0.0147, 0.0161, 0.0149,
        0.0159, 0.0152, 0.0150, 0.0156, 0.0158, 0.0167, 0.0164, 0.0158, 0.0146,
        0.0156, 0.0158, 0.0159, 0.0153, 0.0147, 0.0159, 0.0160, 0.0164, 0.0157,
        0.0147, 0.0158, 0.0156, 0.0155, 0.0156, 0.0160, 0.0162, 0.0157, 0.0151,
        0.0159, 0.0165, 0.0165, 0.0153, 0.0158, 

 tensor([0.0226, 0.0062, 0.0097, 0.0126, 0.0095, 0.0021, 0.0018, 0.0040, 0.0026,
        0.0105, 0.0108, 0.0088, 0.0085, 0.0161, 0.0033, 0.0291, 0.0442, 0.0124,
        0.0084, 0.0124, 0.0056, 0.0139, 0.0048, 0.0497, 0.0094, 0.0054, 0.0092,
        0.0299, 0.0005, 0.0045, 0.0468, 0.0112, 0.0061, 0.0083, 0.0174, 0.0065,
        0.0034, 0.1611, 0.0034, 0.0059, 0.0024, 0.0155, 0.0207, 0.0051, 0.0255,
        0.0172, 0.0215, 0.0426, 0.0010, 0.0017, 0.0112, 0.0238, 0.0252, 0.0458,
        0.0229, 0.0138, 0.0126, 0.0046, 0.0072, 0.0033, 0.0190, 0.0052, 0.0095,
        0.0035])

ID: 171
PKG: about-py
VEC:
 tensor([0.0161, 0.0151, 0.0146, 0.0151, 0.0155, 0.0162, 0.0147, 0.0161, 0.0149,
        0.0159, 0.0152, 0.0150, 0.0156, 0.0158, 0.0167, 0.0164, 0.0158, 0.0146,
        0.0156, 0.0158, 0.0159, 0.0153, 0.0147, 0.0159, 0.0160, 0.0164, 0.0157,
        0.0147, 0.0158, 0.0156, 0.0155, 0.0156, 0.0160, 0.0162, 0.0157, 0.0151,
        0.0159, 0.0165, 0.0165, 0.0153, 0.0158, 0.0155, 0.0152, 0.0158, 0

 tensor([0.0161, 0.0151, 0.0146, 0.0151, 0.0155, 0.0162, 0.0147, 0.0161, 0.0149,
        0.0159, 0.0152, 0.0150, 0.0156, 0.0158, 0.0167, 0.0164, 0.0158, 0.0146,
        0.0156, 0.0158, 0.0159, 0.0153, 0.0147, 0.0159, 0.0160, 0.0164, 0.0157,
        0.0147, 0.0158, 0.0156, 0.0155, 0.0156, 0.0160, 0.0162, 0.0157, 0.0151,
        0.0159, 0.0165, 0.0165, 0.0153, 0.0158, 0.0155, 0.0152, 0.0158, 0.0149,
        0.0150, 0.0168, 0.0151, 0.0156, 0.0159, 0.0157, 0.0162, 0.0157, 0.0160,
        0.0150, 0.0157, 0.0151, 0.0152, 0.0161, 0.0159, 0.0156, 0.0156, 0.0157,
        0.0156])

ID: 377
PKG: activity-feed
VEC:
 tensor([0.0161, 0.0151, 0.0146, 0.0151, 0.0155, 0.0162, 0.0147, 0.0161, 0.0149,
        0.0159, 0.0152, 0.0150, 0.0156, 0.0158, 0.0167, 0.0164, 0.0158, 0.0146,
        0.0156, 0.0158, 0.0159, 0.0153, 0.0147, 0.0159, 0.0160, 0.0164, 0.0157,
        0.0147, 0.0158, 0.0156, 0.0155, 0.0156, 0.0160, 0.0162, 0.0157, 0.0151,
        0.0159, 0.0165, 0.0165, 0.0153, 0.0158, 0.0155, 0.0152, 0.01

 tensor([0.0161, 0.0151, 0.0146, 0.0151, 0.0155, 0.0162, 0.0147, 0.0161, 0.0149,
        0.0159, 0.0152, 0.0150, 0.0156, 0.0158, 0.0167, 0.0164, 0.0158, 0.0146,
        0.0156, 0.0158, 0.0159, 0.0153, 0.0147, 0.0159, 0.0160, 0.0164, 0.0157,
        0.0147, 0.0158, 0.0156, 0.0155, 0.0156, 0.0160, 0.0162, 0.0157, 0.0151,
        0.0159, 0.0165, 0.0165, 0.0153, 0.0158, 0.0155, 0.0152, 0.0158, 0.0149,
        0.0150, 0.0168, 0.0151, 0.0156, 0.0159, 0.0157, 0.0162, 0.0157, 0.0160,
        0.0150, 0.0157, 0.0151, 0.0152, 0.0161, 0.0159, 0.0156, 0.0156, 0.0157,
        0.0156])

ID: 603
PKG: addicted3
VEC:
 tensor([0.0161, 0.0151, 0.0146, 0.0151, 0.0155, 0.0162, 0.0147, 0.0161, 0.0149,
        0.0159, 0.0152, 0.0150, 0.0156, 0.0158, 0.0167, 0.0164, 0.0158, 0.0146,
        0.0156, 0.0158, 0.0159, 0.0153, 0.0147, 0.0159, 0.0160, 0.0164, 0.0157,
        0.0147, 0.0158, 0.0156, 0.0155, 0.0156, 0.0160, 0.0162, 0.0157, 0.0151,
        0.0159, 0.0165, 0.0165, 0.0153, 0.0158, 0.0155, 0.0152, 0.0158, 

VEC:
 tensor([0.0161, 0.0151, 0.0146, 0.0151, 0.0155, 0.0162, 0.0147, 0.0161, 0.0149,
        0.0159, 0.0152, 0.0150, 0.0156, 0.0158, 0.0167, 0.0164, 0.0158, 0.0146,
        0.0156, 0.0158, 0.0159, 0.0153, 0.0147, 0.0159, 0.0160, 0.0164, 0.0157,
        0.0147, 0.0158, 0.0156, 0.0155, 0.0156, 0.0160, 0.0162, 0.0157, 0.0151,
        0.0159, 0.0165, 0.0165, 0.0153, 0.0158, 0.0155, 0.0152, 0.0158, 0.0149,
        0.0150, 0.0168, 0.0151, 0.0156, 0.0159, 0.0157, 0.0162, 0.0157, 0.0160,
        0.0150, 0.0157, 0.0151, 0.0152, 0.0161, 0.0159, 0.0156, 0.0156, 0.0157,
        0.0156])

ID: 817
PKG: afp
VEC:
 tensor([0.0161, 0.0151, 0.0146, 0.0151, 0.0155, 0.0162, 0.0147, 0.0161, 0.0149,
        0.0159, 0.0152, 0.0150, 0.0156, 0.0158, 0.0167, 0.0164, 0.0158, 0.0146,
        0.0156, 0.0158, 0.0159, 0.0153, 0.0147, 0.0159, 0.0160, 0.0164, 0.0157,
        0.0147, 0.0158, 0.0156, 0.0155, 0.0156, 0.0160, 0.0162, 0.0157, 0.0151,
        0.0159, 0.0165, 0.0165, 0.0153, 0.0158, 0.0155, 0.0152, 0.0158, 0

 tensor([0.0161, 0.0151, 0.0146, 0.0151, 0.0155, 0.0162, 0.0147, 0.0161, 0.0149,
        0.0159, 0.0152, 0.0150, 0.0156, 0.0158, 0.0167, 0.0164, 0.0158, 0.0146,
        0.0156, 0.0158, 0.0159, 0.0153, 0.0147, 0.0159, 0.0160, 0.0164, 0.0157,
        0.0147, 0.0158, 0.0156, 0.0155, 0.0156, 0.0160, 0.0162, 0.0157, 0.0151,
        0.0159, 0.0165, 0.0165, 0.0153, 0.0158, 0.0155, 0.0152, 0.0158, 0.0149,
        0.0150, 0.0168, 0.0151, 0.0156, 0.0159, 0.0157, 0.0162, 0.0157, 0.0160,
        0.0150, 0.0157, 0.0151, 0.0152, 0.0161, 0.0159, 0.0156, 0.0156, 0.0157,
        0.0156])

ID: 1024
PKG: aio-core
VEC:
 tensor([0.0161, 0.0151, 0.0146, 0.0151, 0.0155, 0.0162, 0.0147, 0.0161, 0.0149,
        0.0159, 0.0152, 0.0150, 0.0156, 0.0158, 0.0167, 0.0164, 0.0158, 0.0146,
        0.0156, 0.0158, 0.0159, 0.0153, 0.0147, 0.0159, 0.0160, 0.0164, 0.0157,
        0.0147, 0.0158, 0.0156, 0.0155, 0.0156, 0.0160, 0.0162, 0.0157, 0.0151,
        0.0159, 0.0165, 0.0165, 0.0153, 0.0158, 0.0155, 0.0152, 0.0158, 

In [61]:
print(model['model_state_dict']['topic_embeds'].size())

torch.Size([128, 64])
